name = "no style, please!"
description = "A (nearly) no-CSS, fast, minimalist Zola theme"
license = "MIT"
homepage = "https://git.sr.ht/~gumxcc/zola-no-style-please"
min_version = "0.4.0"
demo = "https://zola-no-style-please.demo.gumx.cc"

[extra]

# The theme author info: you!
[author]
name = "Ahmed"
homepage = "https://gumx.cc"

[original]
author =  "Riccardo Graziosi"
homepage = "https://riggraz.dev"
repo = "https://github.com/riggraz/no-style-please"
